# Generated by Django 4.1.7 on 2023-03-23 04:38

import comic.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0008_alter_comic_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=comic.models.Image.rename_image)),
                ('order', models.IntegerField()),
                ('chap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='comic.chap')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
