# Generated by Django 4.1.7 on 2023-03-29 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0008_alter_comic_author'),
    ]

    operations = [


        migrations.AlterField(
            model_name='comic',
            name='author',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='comic',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), (
                'unisex', 'unisex')], default='unisex', max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='chap/')),
                ('order', models.IntegerField()),
                ('chap', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, related_name='chap', to='comic.chap')),
            ],
        ),
    ]
