# Generated by Django 4.1.7 on 2023-03-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0008_alter_comic_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='author',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
