# Generated by Django 4.1.7 on 2023-03-29 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0009_remove_comic_sumary_comic_summary_alter_comic_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comic',
            name='sumary',
        ),
        migrations.AddField(
            model_name='comic',
            name='summary',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
    ]
