# Generated by Django 4.1.7 on 2023-03-23 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0009_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='comic',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comic', to='comic.comic'),
        ),
        migrations.AlterField(
            model_name='image',
            name='chap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chap_image', to='comic.chap'),
        ),
    ]
