# Generated by Django 4.1.7 on 2023-03-28 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0009_alter_comic_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comic',
            old_name='sumary',
            new_name='summary',
        ),
    ]
