# Generated by Django 4.1.7 on 2023-03-29 03:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0010_remove_comic_sumary_comic_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
