# Generated by Django 4.1.7 on 2023-03-29 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0011_alter_comic_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
