# Generated by Django 4.1.7 on 2023-03-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0013_alter_comic_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='author',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
