# Generated by Django 4.1.7 on 2023-04-13 07:30

import comic.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comic', '0014_alter_comic_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=comic.models.get_image_upload_path),
        ),
        migrations.CreateModel(
            name='Novels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('chap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chap_novels', to='comic.chap')),
            ],
        ),

    ]
