# Generated by Django 4.1.7 on 2023-04-13 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0015_alter_image_image_novels_comment_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Novels',
        ),
    ]
