# Generated by Django 4.1.7 on 2023-04-13 08:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comic', '0017_novels_comment_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='chap',
            name='is_comic',
            field=models.BooleanField(default=0, null=True),
        ),

    ]
