# Generated by Django 4.1.7 on 2023-04-13 09:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comic', '0019_rename_is_comic_chap_is_novel_comment_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novels',
            name='chap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comic.chap'),
        ),

    ]
