# Generated by Django 4.1.7 on 2023-04-13 09:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comic', '0020_alter_novels_chap_comment_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='novels',
            name='is_novel',
            field=models.BooleanField(default=False),
        ),

    ]
