# Generated by Django 4.1.7 on 2023-04-14 11:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comic', '0021_novels_is_novel_comment_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='rating_count',
            field=models.FloatField(default=0, null=True),
        ),

    ]
