# Generated by Django 4.1.7 on 2023-03-28 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0024_chap_images_delete_chapimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chap',
            name='images',
        ),
    ]
