# Generated by Django 4.1.7 on 2023-03-28 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0026_alter_comment_options_comment_like_cmt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
    ]
