# Generated by Django 4.1.7 on 2023-03-28 08:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comic', '0030_remove_likecomment_comment_remove_likecomment_like_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LikeComment',
            new_name='Like',
        ),
    ]
