# Generated by Django 4.1.7 on 2023-03-28 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0032_comment_likes_delete_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='like_cmt',
        ),
    ]
