# Generated by Django 4.1.7 on 2023-03-30 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0034_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='chap',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='comic.chap'),
        ),
        migrations.AddField(
            model_name='history',
            name='removed_history',
            field=models.BooleanField(default=0, null=True),
        ),
    ]
