# Generated by Django 4.1.7 on 2023-03-30 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0035_history_chap_history_removed_history'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ('update_at',)},
        ),
        migrations.AddField(
            model_name='history',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
