# Generated by Django 4.1.7 on 2023-04-03 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0036_alter_history_options_history_update_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likes_num',
            field=models.IntegerField(default=0),
        ),
    ]
