# Generated by Django 4.1.7 on 2023-03-23 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_bookmark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='is_readed',
            new_name='readed',
        ),
    ]
