# Generated by Django 4.1.7 on 2023-03-29 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_is_readed_follow_readed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='chapter',
            new_name='chap',
        ),
    ]
