# Generated by Django 4.1.7 on 2023-03-29 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_chapter_bookmark_chap'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
