# Generated by Django 4.1.7 on 2023-04-13 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
